### ISSUE TITLE
Crash on 0-demo-scenario.scn

### ISSUE THREAD

**Issue by GGurtner** [ProfHoekstra/bluesky#1] opened 2015-07-03 09:37 UTC
Hi, I just tested bluesky and I have a systematic crash. Procedure to reproduce:
 -- load "0-demo-scenario.scn"
 -- wait around 1 minute. Some warning messages appear in the log:
> /home/earendil/Programmes/BlueSky/bluesky/bluesky/traf/asas.py:159: RuntimeWarning: invalid value encountered in less
  *(1.-I)

 -- Click on any aircraft, code AF982 appears instead of its own code in the console. 
 -- Click again on any aircraft, crash with stacktrace:
>Traceback (most recent call last):
  File "bluesky.py", line 98, in <module>
    tmx.run()        # Run it
  File "bluesky.py", line 58, in run
    self.cmd.process()                   # Process commands
  File "/home/earendil/Programmes/BlueSky/bluesky/bluesky/stack/stack.py", line 372, in process
    + str(int(traf.alt[idx] / ft)) + " ft")
ValueError: cannot convert float NaN to integer

Obviously, some numpy arrays related to asas are corrupted by NaN values because at least one aircraft (AF982?) is messing around.

**Comment by ProfHoekstra** [comment] 2015-07-03 13:38
Thanks, we'll have a look at this and see whether we can reproduce this.

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 3 jul. 2015, at 11:37, Gérald Gurtner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I just tested bluesky and I have a systematic crash. Procedure to reproduce:
-- load "0-demo-scenario.scn"
-- wait around 1 minute. Some warning messages appear in the log:

/home/earendil/Programmes/BlueSky/bluesky/bluesky/traf/asas.py:159: RuntimeWarning: invalid value encountered in less
*(1.-I)

-- Click on any aircraft, code AF982 appears instead of its own code in the console.
-- Click again on any aircraft, crash with stacktrace:

Traceback (most recent call last):
File "bluesky.py", line 98, in
tmx.run() # Run it
File "bluesky.py", line 58, in run
self.cmd.process() # Process commands
File "/home/earendil/Programmes/BlueSky/bluesky/bluesky/stack/stack.py", line 372, in process
+ str(int(traf.alt[idx] / ft)) + " ft")
ValueError: cannot convert float NaN to integer

Obviously, some numpy arrays related to asas are corrupted by NaN values because at least one aircraft (AF982?) is messing around.

**Comment by jooste** [comment] 2015-10-02 11:15
Hello all,

This issue should be fixed with the latest commit on perf.py, which fixed a bug in the create aircraft command. The demo scenario now runs beyond simt=1000 sec without warning or error.

**Closed by jooste** 2015-10-02 11:15 UTC
