### ISSUE TITLE
qtgl/nodemanager.py - IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by junzis** [ProfHoekstra/bluesky#42] opened 2016-08-11 10:21 UTC
*****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Reading config from settings.cfg
Using Qt4 for windows and widgets
Initializing multi-process simulation
QGLWidget initialized for OpenGL version 3.3
OpenGL context created with GL version 2.1
Reading config from settings.cfg
Traceback (most recent call last):
  File "/home/junzi/Desktop/bluesky/bluesky/ui/qtgl/radarwidget.py", line 160, in actnodeChanged
    self.allpolys.set_vertex_count(len(nact.polydata) / 2)
AttributeError: 'RadarWidget' object has no attribute 'allpolys'
junzi@ubuntu:~/Desktop/bluesky$ Traceback (most recent call last):
  File "BlueSky_qtgl.py", line 83, in <module>
    MainLoop()
  File "BlueSky_qtgl.py", line 44, in MainLoop
    runNode()
  File "/home/junzi/Desktop/bluesky/bluesky/sim/qtgl/nodemanager.py", line 20, in runNode
    manager.sim.doWork()
  File "/home/junzi/Desktop/bluesky/bluesky/sim/qtgl/simulation.py", line 96, in doWork
    self.stack.process(self, self.traf, self.screenio)
  File "/home/junzi/Desktop/bluesky/bluesky/stack/stack.py", line 707, in process
    results = function(*arglist)  # * = unpack list to call arguments
  File "/home/junzi/Desktop/bluesky/bluesky/sim/qtgl/screenio.py", line 113, in pan
    self.manager.sendEvent(PanZoomEvent(pan=(self.ctrlat, self.ctrlon), absolute=True))
  File "/home/junzi/Desktop/bluesky/bluesky/sim/qtgl/nodemanager.py", line 56, in sendEvent
    self.connection.send((int(event.type()), event))
IOError: [Errno 32] Broken pipe

**Comment by jooste** [comment] 2016-08-11 10:40
Duplicate of issue #37

**Closed by jooste** 2016-08-11 10:40 UTC
